name: spot_me
description: SpotMe is an application to find volunteers

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.5.3
  cloud_firestore: ^0.14.4

  firebase_analytics: ^6.3.0
  firebase_crashlytics: ^0.2.4

  rxdart: ^0.24.1
  geoflutterfire: ^2.2.1
  location: ^3.1.0
  google_maps_flutter: ^1.0.6

  flutter_svg: ^0.19.0

  connectivity: ^2.0.2
  dartz: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
